### Auth
# @name auth
POST https://localhost:5001/users/auth
Content-Type: application/json

{
	"user": {
		"email": "coffee@beanmachine.pro",
		"password": "coffee"
	}
}

@token = {{auth.response.body.$.user.token}}

### List categories
# @name list_categories
GET https://localhost:5001/categories
Content-Type: application/json
Authorization: Bearer {{token}}
